development:
  adapter: postgresql
  encoding: utf8
  database: haiku_app_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: haiku_app_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: haiku_app_production
  pool: 5
  username: 
  password: